### ISSUE TITLE
Please clarify: this plugin does not integrate in any way with the wordpress media gallery?

### ISSUE THREAD

**Issue by COLABORATI** [norbusan/piwigopress#12]
Hi, I am trying to understand what exactly this wordpress piwigo integration does - looks like I can show some pictures in a widget - is there some more? 

So there is no whatsoever integration with the internal wordpress media gallery, no e.g. selecting pictures from piwigo instead of media gallery, or importing of pictures from piwigo to media gallery?

Also there is no integration on a user level, so no mirroring of user accounts etc. ?

All this plugin does right now is receiving some pictures from a piwigo web api and show it in a widget, yes? 

I just want to be sure that I really understand what this does, THANKS!

**Comment by norbusan** [comment]
More or less you are right. What it does:
* provide a widget to list categories and pull in photos
* provide a *shortcode* to include images: this is my main usage, I have all my photos in a piwigo web gallery, and do *not* want to re-upload them to wordpress

What it *not* does, as you mentioned:
* user sync
* integration into the media gallery - but you have a shortcode creator button above the editor, to easily select photos and create/insert the respective shortcode

Hope that helps. If you have any other question, please let me know (and reopen the issue).

Norbert

**Comment by COLABORATI** [comment]
Thanks for the info, have a nice day!
