### ISSUE TITLE
warning on wordpress.org

### ISSUE THREAD

**Issue by plegall** [norbusan/piwigopress#27]
It seems wordpress.org is warning users to avoid PiwigoPress because it hasn't been updated for a long time.
![screenshot-2018-2-9 piwigopress 1](https://user-images.githubusercontent.com/9326959/36037800-1c775e1c-0dbe-11e8-9c33-e4e92ecff070.png)

I have also received an email from a user saying Wordpress is preparing a major technical update and plugin will/may need to change their code too.

**Comment by norbusan** [comment]
Thanks, I updated the plugin page to reflect reality that it works with current Wordpress version!
