### ISSUE TITLE
Some remote galleries don't work

### ISSUE THREAD

**Issue by norbusan** [norbusan/piwigopress#5]
Depending on the way they are accessed, some galleries do not work. 
Example:: http://www.gouyet.org/piwigo/
categories are loaded, but photo download does not work

**Comment by dkebler** [comment]
Could this be my issue.  

after install

1. enter in the url, tried pwigo demo first.   http://piwigo.org/demo/
2. click "load list of categories" (btw what is a category? an album?, keywords?)
3. No items are added to the dropdown just lists "all categories/photos"
4. then click get "most recent"

comes back with error

Notice: unserialize(): Error at offset 0 of 9896 bytes in /var/www/duranguito.org/wp-content/plugins/piwigopress/thumbnails_reloader.php on line 38

tried it with my install too at his url
http://photos.healthwrights.org
same deal only no error message even, no thumbs either.

Any thoughts.   

If I can't get this to work what is the shortcode syntax so I can just add photos manually.

**Comment by norbusan** [comment]
Hi

First of all, I see the same with not being able to load the categories (which are albums, sorry, will change the name) for the piwigo demo. I need to investigate, but I believe that something is blocking this due to cross site policy. I investigated at some point, and couldn't find a solution.

But the, I get thumbnails properly loaded from the piwigo demo gallery, so there is something strange at your side.

Do you have any javascript blockers or similar installed? ANything interfering with normal operation?

**Comment by norbusan** [comment]
Ok, I go tthis now working. The problem was cross site scripting with javascript. It is in the dev version, and I will release soon.
